name: CD

# NOTE: Don't update this
on:
  push:
    branches:
      - main

jobs:
  test_build:
    name: Run Tests + Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - uses: actions/cache@v3
        id: data-cache
        with:
          path: cache
          key: data-cache

      - name: Run yarn install
        run: yarn install

      - name: Build + Test
        run: yarn build
        timeout-minutes: 30
        env:
          # Common
          NODE_OPTIONS: --max_old_space_size=4096
          # App ENV
          NEXT_PUBLIC_POSTHOG_KEY: phc_oJiIyzhBjXMhfkqNAAU2flwbYdfepWg7Z9RU0x4RWRk

      - name: Upload GH artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: out/

  deploy:
    name: Deploy (GH Page)
    needs: test_build
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v2
