name: CI

on:
  pull_request:
  push:
    branches:
      - 'develop'

env:
  GITHUB_WORKFLOW: true

jobs:
  ci:
    name: Lint + Type Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'yarn'

      # Pre-commit
      - uses: actions/setup-python@v4
      - name: Install pre-commit
        run: pip install pre-commit

      - name: Pull submodules (Server)
        run:
          git submodule update --init --recursive

      - name: Install dependencies
        run: yarn install --prefer-online

      - name: Check
        run: pre-commit run -vvv --all-files

      # FIXME: Check build after creating fixtures
